### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by sondra-kinsey** [dgmltn/AndieGraph#1]
You've got a 404 on the link to http://dgmltn.com/roms
It is linked to both from the page https://play.google.com/store/apps/details?id=net.supware.tipro
as well as inside the application in the error message: "No ROM was found on your SD card. help[link]".

**Comment by corsairmarks** [comment]
Thanks for the issue.  However, this is not the official repo.  I forked from https://github.com/dgmltn/AndieGraph and I recommend you contact @dgmltn, the official maintainer.

**Comment by dgmltn** [comment]
Ok, the link is fixed! Thanks for the bug report.
