### ISSUE TITLE
Getting started with ROM

### ISSUE THREAD

**Issue by sondra-kinsey** [dgmltn/AndieGraph#2]
I have two ROMs, a .8eu and a .8Xu. I downloaded them from my email. When I start AndieGraph, I get a message "No ROM was found on your SD card. help[link]". Presumably, the ROMs aren't located in a spot Andie Graph can find them. Where should I put them?
It would be nice if AndieGraph could launch an open dialog to find them, but maybe that isn't the Android way; I am new to Android.

**Comment by corsairmarks** [comment]
From my experience using AndieGraph as a user, it expects to find the ROMs at the root (top level folder) of your SD Card or your phone memory.

I recommend checking the official repo from @dgmltn here https://github.com/dgmltn/AndieGraph

**Comment by dgmltn** [comment]
Additionally, you should name it something like "TI82.ROM". Andie Graph is somewhat lenient with the names of the files; it looks for "*82*.ROM", case insensitively, with the proper file size.

From experience, though, I'm guessing that your .8eu and .8Xu files aren't actual ROM files. They're more like an incremental update to an existing ROM. You'll need the full thing. Here's the best way to extract the ROM from the calculator you own: http://www.ticalc.org/programming/emulators/
