### ISSUE TITLE
Any possibility getting Andie Graph back in Google Play Store?

### ISSUE THREAD

**Issue by qzcw** [dgmltn/AndieGraph#5]
Please, try to get it back. I am so devastated that AndieGraph isn't anymore available to download for Android. I simply loved that simple calculator. As a TI-86 owner, I love to have the same calc running also on my phone.

**Comment by dgmltn** [comment]
AlmostTI is newer and better, and available on the App Store, here: https://play.google.com/store/apps/details?id=com.fms.ati
